# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: javialva <javialva@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/06/12 12:31:44 by javialva          #+#    #+#              #
#    Updated: 2024/06/12 20:24:37 by javialva         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_name
CFLAGS = -Wall -Wextra -Werror
CFILES = display_file.c

all: 
	gcc $(CFLAGS) -o $(NAME) $(CFILES)

clean:
	/bin/rm -f *.o

fclean:
	/bin/rm -f $(NAME)
